### ISSUE TITLE
Add feature to allow testing/templating of multiscrape sensors

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#104]
**Is your feature request related to a problem? Please describe.**
When I set up a new mutliscrape sensor, where I have to perform a template operation  on the scraped output, there isn't really any way to test this apart from editing the configuration.yaml and reloading everything. This is a bit slow.

**Describe the solution you'd like**
I'd love some way of playing in the Developer Tools with mutliscrape's output -- maybe some sort of optional dummy sensor which would contain the raw scraped data for which the value_template could be edited and then pasted back into the final configuration.yaml. 

**Additional context**
I scrape multiple sensors from a single webpage, together with attributes to them, so maybe that's my difficulty.

**Comment by melwinek** [comment]
For testing I use
https://github.com/AlexxIT/HassWP
Clean install only with multiscrape starts very fast.
;)

**Comment by wigster** [comment]
I see what you mean, I don't know why this didn't cross my mind -- I should just scrape with no template, play until satisfied and then correct the configuration. This makes sense. Please close.
