### ISSUE TITLE
Schedule for scraping interval

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#109]
**Is your feature request related to a problem? Please describe.**
I would like to be able to vary how often multiscrape makes a page request, depending on a schedule. This is for those websites where I can query the API for free a limited number of times per day. E.g. I would like to get weather updates once every 15 minutes during the day but once an hour at night.

**Describe the solution you'd like**
One idea would be to let the `scan_interval` be read from a helper, which I could adjust as I see fit with my own automations. If that's not possible, then maybe a peak/off-peak scanning interval with some start and end times for these?

**Describe alternatives you've considered**
I could set the scan_interval to once every 24h and write an automation to do trigger the scan manually. But this gets bulky quickly.

**Comment by danieldotnl** [comment]
I think the alternative you describe is the way to go. 
Creating schedules is non-core functionality to multiscrape and therefore making multiscrape bulky.
