### ISSUE TITLE
Latest releases disappeared from repository

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#119]
## Version of the custom_component

v6.0.1

## Describe the bug

It seems that the newer versions of multiscrape have disappeared from this repository -- I "updated" from 6.2.x to pre-6.0.1 when it was offered last night without looking and now my sensors no longer have units. I have just noticed that anything newer than 6.0.1 is gone from the releases, which is what caused this to be offered in the first place, as far as I can surmise.

**Comment by danieldotnl** [comment]
I had the same thing happening, but it also recovered by itself. All releases are back there without me doing anything...
