### ISSUE TITLE
Check for a certain word(s) before update devices.

### ISSUE THREAD

**Issue by malosaa** [danieldotnl/ha-multiscrape#142]
Hi @danieldotnl 

FIrst of all thanks for this aswome add-on.

Well i have a feature request, and i'm not sure if this is possible but i'm asking anyway.

Is there a way to first check the scrape that it contains a certain word before it actually scrapes the data?
Or it scrapes but it only update the data if it contains my word(s) 

regards

regards

**Comment by mhaas** [comment]
Perhaps you can achieve this by adding two scrape sensors. First sensor checks for the word. An automation can trigger the second scraper/sensor if the word is found based on a state change of the sensor.

**Comment by malosaa** [comment]
> Perhaps you can achieve this by adding two scrape sensors. First sensor checks for the word. An automation can trigger the second scraper/sensor if the word is found based on a state change of the sensor.

Thanks for the reply,
So basically what you say is that i scrape the site, and let another automation check for the word and update another sensor?
This would be great if it can copy exactly the same sensor with all the attributes, as i need all the data then.
So i will need to use a template then.

It would be easyer if i can do this in one go instead of having a couple automations trigger.

Or can you show me an example?

many thanks, regards

**Comment by danieldotnl** [comment]
I also think that using a template sensor is the best solution. Of course having it in one go would be easier, but I don't see this as a common use case. Adding all kind of non-core features will make it very hard to keep this component maintainable.

**Comment by malosaa** [comment]
> I also think that using a template sensor is the best solution. Of course having it in one go would be easier, but I don't see this as a common use case. Adding all kind of non-core features will make it very hard to keep this component maintainable.

Yeah thats true, well anyway thanks for your reply.
As i now need to find out how i can achieve what i want.

Have a nice day.

**Comment by malosaa** [comment]
Sounds great,
So how could i quick to that in an automation,
