### ISSUE TITLE
Using template as payload

### ISSUE THREAD

**Issue by booroondookZ** [danieldotnl/ha-multiscrape#149]
I want to make REST requests with POST method.
If I use constant string as payload...
```
      payload: >-
        {"action":"getDeviceInfo","deviceId":"XXXXX","login":"xxxxxxx","key":"xxx-xxx-xxx"}
```
all work fine.
But if I use template as payload...
```
      payload: >-
         {{states('input_text.my_payload')}}
```
integration does not work correctly despite the fact that the correct value is returned in the template engine:
`{{states('input_text.my_payload')}} = {"action":"getDeviceInfo","deviceId":"XXXXX","login":"xxxxxxx","key":"xxx-xxx-xxx"}`
In page_soup.txt, I see that the server is returning a bad result, which indicates that the payload was incorrect.
Unfortunately, there is nowhere in the logs to find out which payload exactly was sent to the server.:

**Comment by danieldotnl** [comment]
Looks indeed like templates are not supported for the payload. Will add it as soon as I have time.

**Comment by danieldotnl** [comment]
Please check release v6.4.0 and confirm that it's working now for you.

**Comment by booroondookZ** [comment]
> Please check release v6.4.0 and confirm that it's working now for you.
Fantastic! It works! Thank you very much!
