### ISSUE TITLE
Merge multiple selects into one result

### ISSUE THREAD

**Issue by craigueh** [danieldotnl/ha-multiscrape#160]
Thanks for this great addon :-)

Is it possible to scrape two bits of data, e.g a h2 tag and subsequent p tag and merge the data as one result.

Like this

<h2>TODAY - Thursday 20th October</h2>
<p>Largely dry and sunny this afternoon and it will be mild for October with highest temperatures of 15 to 17 degrees.</p>

and have it returned as 
"TODAY - Thursday 20th October - Largely dry and sunny this afternoon and it will be mild for October with highest temperatures of 15 to 17 degrees."

I tried scraping the whole div.forecast but there is a lot of other data I want to exclude as it goes beyond the 255 character limit.

Or maybe I'm doing it all wrong, should I be scraping as a text sensor or something else instead?

**Comment by craigueh** [comment]
Sorry, I should have read the docs more first. I see the select_list option does exactly this.

Is it possible to amend the output with a template to add a space or something after the comma as the results have incorrect spacing between them.

e.g

TODAY - Thursday 20th October,Largely dry and sunny

Thanks.

**Comment by danieldotnl** [comment]
I would suggest to scrape as 2 different attributes and combine them they way you want in either your frontend or a template sensor.

**Comment by craigueh** [comment]
Thanks, I have it working as needed now.
