### ISSUE TITLE
Template support for params

### ISSUE THREAD

**Issue by notabene00** [danieldotnl/ha-multiscrape#163]
**Is your feature request related to a problem?**
Can't use `Yandex.Schedule API` with this component
It is not possible to define template key/value (API needs date in `ISO 8601` format) in params 
**Describe the solution you'd like**
Add template support to `params` configuration option just like in restful sensor

**Additional context**
<img width="412" alt="Снимок экрана 2022-10-25 в 23 12 25" src="https://user-images.githubusercontent.com/9576189/197872353-aba809dc-46f8-42bf-ae2b-6bb0a3d0061f.png">

**Comment by danieldotnl** [comment]
Please check the latest [pre-release](https://github.com/danieldotnl/ha-multiscrape/releases/tag/pre-v6.6.0)!

**Comment by notabene00** [comment]
> Please check the latest [pre-release](https://github.com/danieldotnl/ha-multiscrape/releases/tag/pre-v6.6.0)!

yep, works like a charm
amazing, thanks 👍🏼
