### ISSUE TITLE
new configuration option to specify how value should be returned with select_list

### ISSUE THREAD

**Issue by Fonzy007** [danieldotnl/ha-multiscrape#165]
**Problem description**
Using select_list, the values returned are in the form
`value1,value2,value3`
, if one of the values contains a `,`, then splitting the values by `,` leads to improper results.
For example, if `value1=test`, `value2=1,5`, and `value3=blah`, the value returned is `test,1,5,blah`.
Doing something like this (e.g. in value_template):
`{% set value=value.split(',') %}`
returns
```
value[0]=test
value[1]=1
value[2]=5
value[3]=blah
```
The desired outcome is
```
value[0]=test
value[1]=1,5
value[2]=blah
```
**Describe the solution you'd like**
It would be great to have a new option to specify that returned values should be an array instead of string.
It could be something like
```
as_array: True|False
```

**Describe alternatives you've considered**
An alternative would be to have a new option to specify which separator to use when concatenating values.
It could be something like
```
separator: "my_separator"
```

Thanks in advance 
Francois

**Comment by danieldotnl** [comment]
Please check the latest [pre-release](https://github.com/danieldotnl/ha-multiscrape/releases/tag/pre-v6.6.0)!

**Comment by Fonzy007** [comment]
Hi @danieldotnl ,
Thanks a lot for the improvement. Exactly what I needed for my use case.
