### ISSUE TITLE
Wait for x seconds before scraping the data

### ISSUE THREAD

**Issue by calonsog78** [danieldotnl/ha-multiscrape#167]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying to get the total cumulated power consumed from my energy supplier (https://www.energiaxxi.com/oficina/Mi-consumo.html), however after authenticating with the form-submit, it seems the page is still loading (it has some kind of lazy loading in the components). As you can see page_soup is showing that this div is still loading (it just takes few seconds, and data is refreshed):

```
<div class="md-option__data-graphic positionRelative">
<div class="md-option__data-graphic__kwh">
<label class="kwh_loading">
<span class="text-bold">--</span> kWh
                    </label>
<label class="kwh_calculate">
<span>Calculando consumo </span>
</label>
</div>
```

**Describe the solution you'd like**
I believe it can be interesting to add an option to wait for x seconds before scraping the data.
Checking other scrapers like Selenium, it would be something similar as implement the feature implicitly_wait (from the webdriver)

Thanks in advance
Carlos

**Comment by B1rdEater** [comment]
I'll second that! I have a webpage that first displays HTML, and after a few seconds a JSON. I need the JSON, but can't reach it because the HTML blocks my scraping

**Comment by calonsog78** [comment]
I investigated a little bit further and the root cause are the ajax calls in background. Website calls the APIs to get the info but as it takes some seconds, it shows a preview of the web to have a better UX experience while API is retrieving data...
It would be really helpful...

**Comment by danieldotnl** [comment]
This scraper is not a full-blown web browser. It retrieves the html but does not execute javascript and thus does not retrieve the json in background requests. Waiting x seconds does not solve that.
Try to retrieve/scrape the url of the (json) background request directly instead.
