### ISSUE TITLE
Local variable 'coordinator' referenced before assignment

### ISSUE THREAD

**Issue by doppiaemme** [danieldotnl/ha-multiscrape#172]
## Version of the custom_component

latest available in HACS

-->

## Configuration

- platform: multiscrape
  name: HA scraper
  resource: https://www.home-assistant.io
  scan_interval: 3600
  sensor:
    - unique_id: ha_latest_version
      name: Latest version
      select: ".current-version > h1:nth-child(1)"
      value_template: '{{ (value.split(":")[1]) }}'
    - unique_id: ha_release_date
      icon: >-
        {% if is_state('binary_sensor.ha_version_check', 'on') %}
          mdi:alarm-light
        {% else %}
          mdi:bat
        {% endif %}
      name: Release date
      select: ".release-date"
  binary_sensor:
    - unique_id: ha_version_check
      name: Latest version == 2021.7.0
      select: ".current-version > h1:nth-child(1)"
      value_template: '{{ (value.split(":")[1]) | trim == "2021.7.0" }}'
      attributes:
        - name: Release notes link
          select: "div.links:nth-child(3) > a:nth-child(1)"
          attribute: href

## Describe the bug

Get this error in the logs: local variable 'coordinator' referenced before assignment

## Debug log

Logger: homeassistant.components.sensor
Source: custom_components/multiscrape/sensor.py:55
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 12:43:04 PM (1 occurrences)
Last logged: 12:43:04 PM

Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/multiscrape/sensor.py", line 55, in async_setup_platform
    if not coordinator.last_update_success:
UnboundLocalError: local variable 'coordinator' referenced before assignment

**Comment by danieldotnl** [comment]
Please take the config sample from the readme, starting with: 

`multiscrape:`
