### ISSUE TITLE
two step login form

### ISSUE THREAD

**Issue by ElGauchooooo** [danieldotnl/ha-multiscrape#176]
First of all - great integration!

I'm currently trying to scrape the processing step of a car i've ordered via "meinauto.de". Unfortunatelly, the login form, which can be found at "https://kundencenter.meinauto.de/" offers a bad UX, which has a multi-step login form. 

* First, you have to enter your email, then submit.
* Then, you have to enter your password. 

As far as i can see, this is currently not supported by ha-multiscrape, or am i wrong?

**Comment by danieldotnl** [comment]
That's indeed not supported, unless there is still a single authentication call after the last step with both the username and the password. You'll need to dive into the browser's developer tools to find out.

**Comment by elchininet** [comment]
Hi @danieldotnl,
Is there any possibility of looking into this?
Login in two steps is expanding more each day, and most of them make a call to the server first with the email and then a second with the password, and the first call is needed to set up different cookies and tokens.

Some examples:

| Site | URL |
| ---- | ---- |
| Eneco | https://inloggen.eneco.nl |
| Booking.com | https://account.booking.com/sign-in |
| Disney Plus | https://www.disneyplus.com/nl-nl/login |
| Expedia | https://expedia.com/login |

Regards
