### ISSUE TITLE
conversion from string to number.

### ISSUE THREAD

**Issue by ilmisu** [danieldotnl/ha-multiscrape#186]
dear all,
thank for the very nice tool.
I'm getting an issue, in scraping a value that is fetched as a string, but I'd like to get that as float, to be able to make calculations.
could you please help me in how to template it below the section of the fetched sensor?
thank you

**Comment by roumano** [comment]
> dear all, thank for the very nice tool. I'm getting an issue, in scraping a value that is fetched as a string, but I'd like to get that as float, to be able to make calculations. could you please help me in how to template it below the section of the fetched sensor? thank you

Hi,
Please found a example how to parse the value of multiscrape and convert it integer (replace int with float for you usage ) 
```
    value_template: "{{ value_json.PARAM_NB_J_BLEU | int }}"
```
You should try and test it on dev-tools before updating your code.
