### ISSUE TITLE
Add an on_error icon selection

### ISSUE THREAD

**Issue by ecoen66** [danieldotnl/ha-multiscrape#190]
I would like to propose that the on_error setting for a sensor should include an icon selection.  I currently use multiscrape to create multiple sensors from my Cisco Deskpro video phone, one of which is call status.  If the Deskpro is on a call, I can grab the status using select: "Status > Call > Status".  However, if it is not on a call then there is no "Status > Call" section in the XML result.

In this case I use on_error to set the default state as "idle".  Unfortunately, I cannot change the icon if the result was the "on_error" state.

Here is a snippet of my current config:

multiscrape:
  - name: Deskpro scraper
    resource: "https://192.168.1.23/status.xml"
    authentication: basic
    verify_ssl: false
    username: !secret deskpro_username
    password: !secret deskpro_password
    sensor:
      - unique_id: deskpro_call
        name: Deskpro Call Status
        select: "Status > Call > Status"
        on_error:
          value: default
          default: idle
        icon: >-
          {% if value == 'Connected' %}
            mdi:phone-in-talk
          {% else %}
            mdi:phone-hangup
          {% endif %}

**Comment by danieldotnl** [comment]
Now (finally...) support in v6.7.0!
