### ISSUE TITLE
Error with 2023.7.1

### ISSUE THREAD

**Issue by sagitt** [danieldotnl/ha-multiscrape#215]
i not received any error with 2023.7.0, but with 2023.7.1 i see:

```
Logger: homeassistant.setup
Source: core.py:1763
First occurred: 00:03:36 (1 occurrences)
Last logged: 00:03:36

Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 89, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 162, in _async_process_config
    await _register_services(hass, target_name, coordinator)
  File "/config/custom_components/multiscrape/__init__.py", line 208, in _register_services
    async_set_service_schema(hass, DOMAIN, target_name, service_desc)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 687, in async_set_service_schema
    response := hass.services.supports_response(domain, service)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in supports_response
    if not (handler := self._services[domain][service]):
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'valori_pun_orario'
```

**Comment by ornative** [comment]
Same issue here.

**Comment by greggotcher** [comment]
Same issue as well.

**Comment by tozzke** [comment]
Just updated to 2023.7.1 and experiencing the same issue

**Comment by codyc1515** [comment]
I tried a rudamental fix of this but couldn't work it out. Not clear to me if it's a core bug or multiscrape but leaning towards a multiscrape issue.

**Comment by elupus** [comment]
I think you are lacking service descriptions.

**Comment by miczu71** [comment]
same here

**Comment by Ameglialuna** [comment]
same here

**Comment by fereehu** [comment]
same here with 2023.7.1

**Comment by scrichab** [comment]
same here - after downgrade to my last working core 2023.6.3 it works

**Comment by woopstar** [comment]
same here with 2023.7.1

**Comment by dr2-Romek** [comment]
same here after HA core 2023.7.1 update

**Comment by bdraco** [comment]
> I think you are lacking service descriptions. It does look like a core regression. But may be a bit hard to report since it's a custom integration triggering it.

It looks like async_set_service_schema is being called with a different service name than what is actually be registered

**Comment by hmmbob** [comment]
Rollback to 2023.7.0 does solve the issue. https://github.com/home-assistant/core/pull/95911 was in 2023.7.1, so might very likely be the reason for this failing now, as @elupus said.

**Comment by danieldotnl** [comment]
Thanks @bdraco, you were right. Fixed in v6.7.1!

**Comment by woopstar** [comment]
Can confirm 6.7.1 is working.

**Comment by hmmbob** [comment]
Confirming the same, HA 2023.7.1 and Multiscrape 6.7.1 work nicely now. Thanks for the quick fixes by all involved!

**Comment by codyc1515** [comment]
Fixed by https://github.com/danieldotnl/ha-multiscrape/commit/683d63f0f1176ea75a99f5bcb407f62999c45295
