### ISSUE TITLE
New setup does not work

### ISSUE THREAD

**Issue by goetzpil** [danieldotnl/ha-multiscrape#224]
Hello,

I'm new to this integration, I've done any mistake, I don't even see an entity with error or any log..

my config.yaml:

![image](https://github.com/danieldotnl/ha-multiscrape/assets/124438978/52164cfe-a076-428d-a456-4d0c64cebcf2)

![image](https://github.com/danieldotnl/ha-multiscrape/assets/124438978/5f1a2c54-c4e5-47da-af48-9e1a4a8956c1)

Problem 1:
![image](https://github.com/danieldotnl/ha-multiscrape/assets/124438978/805136da-389d-45c2-bbbb-a63ad6b2bdc8)

That's the login page:
https://mygridbox.viessmann.com/login

Thats the page where I want to get the value from:

https://mygridbox.viessmann.com/live-view (if I want to open it, i will be redirected to the login page first..)
![image](https://github.com/danieldotnl/ha-multiscrape/assets/124438978/7c6326ce-ebbf-4d70-ab7f-ba2e0f39a37d)

**Comment by danieldotnl** [comment]
Might be a yaml issue, try to put E-Mail between quotes.

**Comment by renarena** [comment]
you have 2 `select:` lines => duplicate

**Comment by danieldotnl** [comment]
@renarena good catch!

**Comment by goetzpil** [comment]
> you have 2 `select:` lines => duplicate

Hey,

Thanks, how do I have to write it Correctly?

**Comment by renarena** [comment]
only use one select: line per sensor

**Comment by goetzpil** [comment]
Well but I have to enter username and password

rena ***@***.***> schrieb am Mo., 24. Juli 2023, 17:10:

**Comment by renarena** [comment]
https://github.com/danieldotnl/ha-multiscrape/wiki/Form-submit-functionality
only use one select: line per form_submit. 
The select: is for the form, not the inputs.

**Comment by danieldotnl** [comment]
I'll close the issue as this is not meant for support questions. Please use the HA forums for that.
