### ISSUE TITLE
Scrape at a specific time

### ISSUE THREAD

**Issue by wautersj** [danieldotnl/ha-multiscrape#225]
**Is your feature request related to a problem? Please describe.**
I am scraping some data from a weather station website. It often is published, but the most interesting data is published relatively Live. 
I dont want to stress the server by over-scraping; and by result; them blocking me.

**Describe the solution you'd like**
An option to ‘schedule’ a scrape at a specific time! It’s oke if i can only define 1 timestamp or so. The interval options are still very oke to use on top of that (they should not be related).

**Comment by danieldotnl** [comment]
You can trigger a scrape action at a specific time by creating an automation that calls the `multiscrape.trigger_{your_config}` service at the desired time.
