### ISSUE TITLE
Can not scrape data from web page

### ISSUE THREAD

**Issue by tgisop** [danieldotnl/ha-multiscrape#230]
Hi,
I am experiencing a problem with retrieving data from a web page.
Specifically I want to get the data from :
body > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(2) > font:nth-child(1) > strong:nth-child(1) > font:nth-child(1) > small:nth-child(1) retrieved from http://perachora-davis.meteoclub.gr/
I've tried everything but it doesn't bring me any data.
I have tried with other fields and the result is the same.

Can you help me?  What can go wrong?

Thanks
Isopoulos Anastasios

**Comment by tgisop** [comment]
Good evening
Thank you for the prompt response.
I tried what you wrote but unfortunately it had no result.
I tried : "table > tr:nth-child(7) > td:nth-child(2) > p:nth-child(7)
and "table > tr:nth-child(7) > td:nth-child(2) > font > b"

Thank you

**Comment by tgisop** [comment]
Yes but with no success 😭

**Comment by redlefloh** [comment]
I looked at the source of the page and it looks like you're trying yo retrieve everything in the red box:

![image](https://github.com/danieldotnl/ha-multiscrape/assets/24863182/b903efc0-56e9-4077-8b86-0607f374e33a)
which basically is the following:

`
NW at 0.0 km/hr&nbsp;(<script type="text/javascript">  document.write(Math.round(Math.pow((0.0/3.01),0.66)));</script>0 Bf)<br>
`

Maybe multiscrape gets confused by the additional JS content? 

Does the "Dewpoint" in the tr before at selector:

`body > table:nth-child(1) > tr:nth-child(8) > td:nth-child(2) > font > strong > small > font`

which only has a temperature, no JS in it, work for you? If so, it may be a multiscrape bug?

**Comment by tgisop** [comment]
Yesssss
It is working the Dewpoint value!!!!!!
How can I get the wind now?

Thank you

**Comment by redlefloh** [comment]
if the Dewpoint succeeds, it may well be that the JS in the destination of the wind confuses multiscrape, so I will need to refer to @danieldotnl 's wisdom! 

And note that even if multiscrape worked, you would still need to parse the resulting string:
`
NW at 0.0 km/hr&nbsp;(<script type="text/javascript"> document.write(Math.round(Math.pow((0.0/3.01),0.66)));</script>0 Bf)<br>
` 
to only get "NW" and "0.0 km/hr" which is probably what you are interested in. You can also ask the meteoclub.gr folks to create separate entries, just like you have it for Dewpoint?

**Comment by tgisop** [comment]
So,
Can you guide me how to extract the "NW" and "0.0 km/hr" which I am
interested in?

Thank you

**Comment by redlefloh** [comment]
it depends on whether you can actually get the full data via multiscrape which currently doesn't seem to work and @danieldotnl will need to take a look. Or - if the website would be willing to provide these values in separate table cells - you can scrape it like the Dewpoint. Sorry, but I can't help you much further at this point.

**Comment by tgisop** [comment]
Thanks a lot for your reply
have a nice day

**Comment by danieldotnl** [comment]
@redlefloh Thank you for your kind support!

@tgisop The github issues are not meant for support and you also created already forum posts at two different places where people are also trying to help you. This is not the way.
