### ISSUE TITLE
Values sensor deleted after 7 days - Multiscrape

### ISSUE THREAD

**Issue by marcellomariano** [danieldotnl/ha-multiscrape#231]
Hello Everybody,

i've found the following code to multiscrape euribor values:

multiscrape:
  - name: Euribor
    resource: https://www.euribor-rates.eu/pt/
    scan_interval: 7200
    sensor:
      - unique_id: Euribor_1_week
        select: ".table > tbody > tr:nth-child(1) > td.text-right"
        unit_of_measurement: '%'
        value_template: '{{ value.split(" ")[0].replace(",", ".") }}'
      - unique_id: Euribor_1_month
        select: ".table > tbody > tr:nth-child(2) > td.text-right" 
        unit_of_measurement: '%'
        value_template: '{{ value.split(" ")[0].replace(",", ".") }}'
      - unique_id: Euribor_3_month
        select: ".table > tbody > tr:nth-child(3) > td.text-right" 
        unit_of_measurement: '%'
        value_template: '{{ value.split(" ")[0].replace(",", ".") }}'
      - unique_id: Euribor_6_month
        select: ".table > tbody > tr:nth-child(4) > td.text-right" 
        unit_of_measurement: '%'
        value_template: '{{ value.split(" ")[0].replace(",", ".") }}'
      - unique_id: Euribor_12_month
        select: ".table > tbody > tr:nth-child(5) > td.text-right" 
        unit_of_measurement: '%'
        value_template: '{{ value.split(" ")[0].replace(",", ".") }}'

The code is working as expected and every day i see the updated Euribor value, but when i try to see the historical data stored for these sensors, i see that only the last 7 days values are stored, the other data are deleted/overwritten from the new ones. Is there any change i can do to store more data?

Thanks
Marcello

**Comment by danieldotnl** [comment]
This is not multiscrape-related but probably due to your [recorder](https://www.home-assistant.io/integrations/recorder/) settings. By default data for all entities will be purged from the databases after 10 days (not 7). 
Alternatively, you could have a look at the [statistics charts](https://www.home-assistant.io/dashboards/statistics-graph/) which can be used to visualize the long term statistics.

**Comment by marcellomariano** [comment]
Dear Daniel,

thank you for your precious feedback. I've analysed the recorder setting page you posted and effectively the days should be ten, and if i try to use the Historical chart i see the data till 22nd August:
![image](https://github.com/danieldotnl/ha-multiscrape/assets/122174221/c8765484-0306-4850-8fd9-ba124f8ed074)
I also tried to follow your suggestion using a statistics chart, but when i try to configure it i can't see the sensors i created. Do you know if i have to change my code see them also as statics?

Thanks a lot for your support.
Marcello

**Comment by danieldotnl** [comment]
I believe you need to set the `state_class` [as per this forum post](https://community.home-assistant.io/t/creating-a-long-term-statistics-sensor/547382/2)
