### ISSUE TITLE
Form URL out of the form

### ISSUE THREAD

**Issue by Kijan** [danieldotnl/ha-multiscrape#255]
**Is your feature request related to a problem? Please describe.**
Hi
I am trying to get the timetable from my daughters school.
I got it wo work, but the login drives me crazy.
when i try to login in browser i get the link to the login with a uuid or something. when i put this in the ressource it works. but i dont want to do that manually each day.
so i tried to find out how to do this.
now i saw the link is in the “form_page_response_body.txt”
so can i use a link out of this txt file for the ressource for the form?
it looks like this:
<link rel="canonical" href="xxx" /><title>

**Describe the solution you'd like**
read the URL from the Form body

**Describe alternatives you've considered**
i will try to get the URL with a second scrape

**Comment by jeremicmilan** [comment]
https://github.com/danieldotnl/ha-multiscrape/pull/327 might fix your problem. It will not allow you to set the link directly, but maybe a hack where you set the location redirect header? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location
If this works, please let me know. Looking forward to feedback. :)

**Comment by danieldotnl** [comment]
Please try release [7.1.2](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v7.1.2) and let me know if it addresses your issue!
