### ISSUE TITLE
Adding a header_template capability (or auth bearer?)

### ISSUE THREAD

**Issue by storm1er** [danieldotnl/ha-multiscrape#256]
**Is your feature request related to a problem? Please describe.**
Some API needs a OAuth token / Bearer token

**Describe the solution you'd like**
The token can be refreshed using multiscrape, but the value we get can't be used in headers (`Authorization: Bearer {{ NEW_TOKEN }}` for example)  
We could have either a `headers_template` that would be the same as `headers` which could only work as `List<string, template>`  
or  
We could have a new authentication `Bearer` that take a template value =)

**Describe alternatives you've considered**
None for now

**Additional context**
Can be useful for all server-to-API, thus there's a security weirdness here as one sensor is the OAuth token for the given API. Maybe we could have an option to obfuscate the sensor value in front-end ... dunno if this is feasible

**Comment by codyc1515** [comment]
Similar issue if you want to post to a token URL but that token URL requires a payload that is JSON (as opposed to a simple form).

**Comment by gkivanov** [comment]
+1 to support templates in `headers` similar to the default `scrape` integration in Home Assistant.

**Comment by danieldotnl** [comment]
Support for templates in headers is now available in [v6.8.0](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v6.8.0)!

**Comment by danieldotnl** [comment]
Closing this issue but feedback is still welcome!
