### ISSUE TITLE
Feature request: Make the on-error value persistent

### ISSUE THREAD

**Issue by g1za** [danieldotnl/ha-multiscrape#263]
**Is your feature request related to a problem? Please describe.**
In case of a scraping error the 'last' value is retained, but only until a reboot.
At that point the sensor value becomes "unavailable" and any attributes are not available as well.
This situation persists until the scraping is successful.

**Describe the solution you'd like**
On error, it would be nice to make 'last' value persistent to prevent to lose it in case of a system reboot.
Attributes as well if possible.

**Describe alternatives you've considered**
A workaround is to manually create a template sensor that receives the value from the scarping sensor and updates it only if the state is not "unavailable".

**Comment by danieldotnl** [comment]
Fixed in pre-release [v8.0.1](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v8.0.1). Please give it a try!

**Comment by g1za** [comment]
It looks to be "fixed". Thanks!
