### ISSUE TITLE
Setup of multiscrape is taking over 10 seconds

### ISSUE THREAD

**Issue by codyc1515** [danieldotnl/ha-multiscrape#274]
Facing an error every time that I restart Home Assistant that "Setup of multiscrape is taking over 10 seconds". Not sure why scraping should be blocking start-up.

```
Logger: homeassistant.setup
Source: runner.py:186
First occurred: 21:05:13 (1 occurrences)
Last logged: 21:05:13

Setup of multiscrape is taking over 10 seconds.
```

**Comment by Borgotto** [comment]
Same here

**Comment by codyc1515** [comment]
I suspect that the processes are not running asychronously.

**Comment by danieldotnl** [comment]
Please try pre-release [v8.0.1](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v8.0.1)!
