### ISSUE TITLE
Multiple sources

### ISSUE THREAD

**Issue by kimsvane** [danieldotnl/ha-multiscrape#281]
Would it be possible to add the possibility to have multiple sources, the reason for this is that i am using it to scrape my outdoor heating unit’s webpage for into. But the information is spread between 2 urls.

**Comment by danieldotnl** [comment]
Could you elaborate a bit more on how you envision this to work? Can't you use a template sensor combining 2 scrape sensors?

**Comment by kimsvane** [comment]
Im new to the multiscrape, and havent done much YAML. 
So i honestly cannot picture how to setup multiple URLS for this, if there's an example on how to it would be appreciated.

**Comment by danieldotnl** [comment]
I recommend you to ask in the community forum a question on what you want to do (in more detail) and how it could be achieved.
