### ISSUE TITLE
Setting Custom Encoding in HA

### ISSUE THREAD

**Issue by matata86** [danieldotnl/ha-multiscrape#283]
Hello,I'm currently using the HA Multiscrape tool for a project, and I've run into an issue with encoding. The webpage I need to scrape uses the Windows 1250 encoding. I've checked the HA Multiscrape documentation but couldn't find any explicit mention of setting custom encoding options. Is there a way to configure HA Multiscrape to handle webpages with specific encodings like Windows 1250? If not, what would be the recommended approach to scrape such pages?Thank you in advance for your assistance!

**Comment by danieldotnl** [comment]
I don't have any experience with this so neither do I have recommended approaches. Does the scrape integration which is part of core home assistant support different encodings?
And what is exactly going wrong when scraping a page in the different encoding?

**Comment by matata86** [comment]
Yes, the default scrape integration supports encoding settings.

If I don't set the encoding, special characters like "scratch" are displayed as question marks.

**Comment by danieldotnl** [comment]
Some time passed.. but can you provide your configuration or a sample config for reproducing this?

**Comment by danieldotnl** [comment]
Feel free to reopen when you have additional info.
