### ISSUE TITLE
Scrapper returning blank text value

### ISSUE THREAD

**Issue by amiler** [danieldotnl/ha-multiscrape#287]
When scrapping a web page from a local EV2 Charger, I am getting a blank value for all text parameters showing on the page (volage, current, power, ...). When inspecting the web page, it shows the following for one of the text elements:

`<output type="text" id="CURRENT" name="CURRENT" value="">5.00</output>`

Value field is indeed blank (nothing between two quotation marks) while the actual value for that text field shows after, between >< signs.

Looking at DEBUG messages from multiscrape, it extract the line like this:

`Tag selected: <output id="CURRENT" name="CURRENT" type="text" value=""></output>`

Is there any way to properly extract the info shown between >< sings so it would be assigned to HA sensor?

**Comment by danieldotnl** [comment]
Most likely, the values are not in the page that is scraped by multiscrape, but are requested in the background and filled by javascript code. This cannot be scraped with multiscrape.
