### ISSUE TITLE
Help - your activity and behavior on this site made us think that you are a bot

### ISSUE THREAD

**Issue by badaxavi** [danieldotnl/ha-multiscrape#298]
Yaml:
- name: Fin Gas
  resource: 'https://areaclientes.comercializadoraregulada.es/ovh-web/Meter/MeterSearch.gas'
  scan_interval: 60
  log_response: true
  form_submit:
    submit_once: False
    #resource: 'https://areaclientes.comercializadoraregulada.es/ovh-web/Login.gas;JSESSIONID_OV=kaptE5INukiaZIIpzwT3mOr6QNfKQwddM1gCoBhV9L_2Ti-mNcar!-1076787600!393165857'
    select: 'form'
    input:
      username: !secret gasnif
      password: !secret gaspass
  sensor:
    - select: "#principal > div.caja-pestana > div > form > div.form-interior > div:nth-child(2) > div.info-group > div > span.text-center > strong"
      name: fechafingas
      unique_id: fechafingas

the log_response:

<!DOCTYPE html>
<html lang="en">
<head>
<title>ShieldSquare Captcha</title>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="https://captcha.perfdrive.com/captcha-public/images/favicon.png" rel="icon"/>
<link href="https://captcha.perfdrive.com/captcha-public/css/shieldsquare_styles.min.css" rel="stylesheet"/>
<script type="text/javascript">
	window.SSJSInternal = 30113;

    var __uzdbm_1 = "8e61fb39-bb66-4806-82e5-5e1077cdf24a";
    var __uzdbm_2 = "Zjg1ZWQ1NzQtYnFrNy00NTBkLWEwYzQtMWE0OWM0NWE1ZDE4JDYyLjU3LjY4LjIxMQ==";

	(function(w, d, e, u, c, g, a, b){
		w["SSJSConnectorObj"] = w["SSJSConnectorObj"] || {ss_cid : c, domain_info: g};
		a = d.createElement(e);
		a.async = true;
		a.src = u;
		b = d.getElementsByTagName(e)[0];
		b.parentNode.insertBefore(a, b);
	})(window,document,"script","https://cdn.perfdrive.com/aperture/aperture.js","b8c3","auto");
</script>
</head>
<body>
<div class="container">
<div class="row">
<div class="col-1">
<img alt="Captcha Page" src="https://captcha.perfdrive.com/captcha-public/images/ss_captcha.png"/>
</div>
<div class="col-2">
<h1>We apologize for the inconvenience...</h1>
<p>...but your activity and behavior on this site made us think that you are a bot.</p>
<p><b>Note:</b> A number of things could be going on here.</p>
<ol>
<li>If you are attempting to access this site using an anonymous Private/Proxy network, please disable that and try accessing site again.</li>
<li>Due to previously detected malicious behavior which originated from the network you're using, please request unblock to site.</li>
</ol>
</div>
</div>
<center><b>Incident ID:</b> f85ed574-bqk7-450d-a0c4-1a49c45a5d18<center>
<div class="row">
<br/>
<div>
<center>
<p><b> Please solve this CAPTCHA to request unblock to the website </b></p>
</center>
</div>
<br/>
<div class="captcha-mid">
<form action="" method="POST" style="width:300px;margin-left:auto;margin-right:auto;">
<script src="https://hcaptcha.com/1/api.js?recaptchacompat=off" type="text/javascript"></script>
<div class="h-captcha" data-sitekey="ae73173b-7003-44e0-bc87-654d0dab8b75"></div><br/>
<center><br/><input class="btn btn-success btn-sm" type="submit" value="Submit"/><br/></center>
</form>
</div>
</div>
</center></center></div>
</body>
<div class="footer">
<div class="footer">
<p class="text-muted credit">
		You reached this page when trying to access
		<b>https%3A%2F%2Fareaclientes.comercializadoraregulada.es%2Fovh-web%2FMeter%2FMeterSearch.gas</b> from
		<b>**.**.**.***</b> on
		<b>December 21 2023, 12:08:33 UTC</b>
</p>
</div>
</div>
</html>

**How can i fix this?**

**Comment by codyc1515** [comment]
You are hitting the website every 60 seconds to, apparently, check your gas meter. Surely your gas meter is not updating this often in the cloud. So, I would suggest changing it to 86400 (once per day). You may need to restart your router / modem in order to get a new IP address.

**Comment by danieldotnl** [comment]
I agree with @codyc1515 and to emphasize this, I added a note on the readme: https://github.com/danieldotnl/ha-multiscrape/commit/a3a2e424aed7eedd5b5350fb81b82b65cc8f578d
Best to contact Fin Gas and ask them for permission to continue scraping.
