### ISSUE TITLE
Expected template to be a string - Multiscrape can not be setup 

### ISSUE THREAD

**Issue by bios2bios** [danieldotnl/ha-multiscrape#312]
Since this morning my multiscrape integration does not work anymore. I did not change anything in the configuration. 
The changes where upgrading multiscrape to the latest and home assistant to the latest

Multitscrape version 6.8.0
HA 2024.1

I tried to revert the multiscrape to the previous version but did not work out and not help in getting rid of the message. I also tried to minimize the number of sensors defined in the configuration. Just only a resource and a simple sensor.

The message in the loggs of HA provide the following information

Logger: homeassistant.setup
Source: setup.py:332
First occurred: 11:04:26 (1 occurrences)
Last logged: 11:04:26

Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 89, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 151, in _async_process_config
    http = _create_scrape_http_wrapper(config_name, conf, hass, file_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 237, in _create_scrape_http_wrapper
    headers_renderer=create_dict_renderer(hass, headers)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/util.py", line 36, in create_dict_renderer
    templates_dict[item] = create_renderer(hass, templates_dict[item])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/util.py", line 15, in create_renderer
    value_template = Template(value_template, hass)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 469, in __init__
    raise TypeError("Expected template to be a string")
TypeError: Expected template to be a string

<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

Issues not containing the minimum requirements will be closed:

## Debug log
I dont even get debug information a it allready fails setting up and does not put the information from the request/response inthe folder.

**Comment by IceDraken** [comment]
I am getting the same since doing the update to home assistant.

This is my error log, and it looks to be the same as yours.

Logger: homeassistant.setup
Source: setup.py:332
First occurred: 7:47:54 AM (1 occurrences)
Last logged: 7:47:54 AM

Error during setup of component multiscrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 89, in async_setup
    return await _async_process_config(hass, entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 151, in _async_process_config
    http = _create_scrape_http_wrapper(config_name, conf, hass, file_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/__init__.py", line 237, in _create_scrape_http_wrapper
    headers_renderer=create_dict_renderer(hass, headers)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/util.py", line 36, in create_dict_renderer
    templates_dict[item] = create_renderer(hass, templates_dict[item])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/multiscrape/util.py", line 15, in create_renderer
    value_template = Template(value_template, hass)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 467, in __init__
    raise TypeError("Expected template to be a string")
TypeError: Expected template to be a string

**Comment by bios2bios** [comment]
I have found a solution for me. I followed the code in the stacktrace and swa it was happening at reading headers from the config. I removed my part of the configuration (which worked for a long time before) and it is working again.

  - resource: !resource_link
    name: name
    log_response: false
    scan_interval: 120
    headers:
      User-Agent: Mozilla/5.0

I removed the headers part and it is working for now. Still i am in favour of having headers so a structural solution is preferred.

**Comment by mjtappert** [comment]
Same error for me on this version of Multiscrape and HA.

**Comment by briadelour** [comment]
I can confirm what @bios2bios reported.  I just commented out the headers section and restarted and multiscrape worked again.
#  headers:
#    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

**Comment by palafix** [comment]
Maybe someone knows how to make a template - list because this section has changed from string - list to template - list.

headers - The headers for the requests. - False  -  template - list

I dont know how to do.
