### ISSUE TITLE
Using unit_of_measurement is causing configuration check to fail

### ISSUE THREAD

**Issue by GalipoliX** [danieldotnl/ha-multiscrape#315]
## Version of the custom_component
Multiscrape 6.8.1
HA 2024.1.2

## Configuration

  - resource: http://172.16.0.12/temp/raw.txt
    scan_interval: 120
    log_response: false
    sensor:

      - unique_id: hz_warmwasser_vorlauf_temp
        name: Heizung Warmwasser Vorlauf Temperatur
        select: "p:nth-child(1)"
        value_template: '{{ (value.split("Warmwasser Vorlauf=")[1].split("\n")[0])}}'
        unit_of_measurement	: "°C"
        device_class: "temperature"
        state_class: "measurement"

## Describe the bug

Using unit_of_measurement in sensor definition is causing HA configuration check to fail

Error loading /config/configuration.yaml: while scanning for the next token
found character '\t' that cannot start any token

Commenting out the UOM Line passes the check but brings the warning:

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hz_warmwasser_vorlauf_temp (<class 'custom_components.multiscrape.sensor.MultiscrapeSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', 'K', '°F']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/danieldotnl/ha-multiscrape/issues

**Comment by danieldotnl** [comment]
I think it is due to the whitespace behind `unit_of_measurement` and the colon.

**Comment by GalipoliX** [comment]
You are my hero!
Drived me nuts ....

Strange thing is that this configuration worked well for over a year now   ....
