### ISSUE TITLE
Dynamic scan_interval

### ISSUE THREAD

**Issue by technotiger** [danieldotnl/ha-multiscrape#320]
**Is your feature request related to a problem? Please describe.**
In the current setup, scan_interval can only be modified in xml. A restart is typically needed to apply the changes.

**Describe the solution you'd like**
It would be great if the scan_interval can be adjusted (get and set) using service calls.

This will make it easier to adhere to ethical and sustainable scraping practices.  Lower scan_intervals could be utilized for short periods as needed; higher scan_interval can be used at other times.

**Describe alternatives you've considered**
It can possibly be done by disabling the scan_interval (by setting to 0), and relying solely on service calls to refresh the scraped data. However, the proposed solution will make it easier and increase adoption.

**Comment by danieldotnl** [comment]
The proposed solution will make the code more complex and harder to maintain with little advantage over the alternative you described :)
So closing this issue.
