### ISSUE TITLE
captcha support automated/manual

### ISSUE THREAD

**Issue by test2a** [danieldotnl/ha-multiscrape#328]
**Is your feature request related to a problem? Please describe.**
i have to scrape my utility website that has a recaptcha on login page.

**Describe the solution you'd like**
either support integration of captcha solving services like there are dozens or allow a method where when user initiates a scrape, user is presented with a popup showing google recaptcha which once solves, gives token to the multiscrape so that login can be done.

**Comment by danieldotnl** [comment]
I'm open to discuss possible solution if you are able and willing to contribute. I will not add this myself.
