### ISSUE TITLE
Add 'Device' id entries

### ISSUE THREAD

**Issue by sdrapha** [danieldotnl/ha-multiscrape#345]
**Describe the solution you'd like**

### Add 'Device' id entries
Add capability to specify a device id, so we can tie together multiple sensor entities under that same device.

**Additional context**
I have multiple and separate entities for a given device among many: battery, signal level, connectivity, temperature.
Attaching them to a specified device would be useful.

Btw, Thanks for this great integration!

**Comment by danieldotnl** [comment]
Unfortunately, devices can only be created by integrations that are set up via a config flow, and not by those set up via yaml.

**Comment by sdrapha** [comment]
ok, thanks for the answer.
