### ISSUE TITLE
Multiscrape ‘slow’ site

### ISSUE THREAD

**Issue by Paul-Vdp** [danieldotnl/ha-multiscrape#361]
I am trying to scrape my provider’s account/subscription status page, but failing big time.
I am pretty sure this is because it must be the slowest site in the universe. Although it only provides me with a rather simple page, it takes very long to show completely - easily up to half a minute. It seems to be generated in at least three stages, automatically refreshing after every stage to show some additional info.
I think the problem is that right after getting to the first stage being shown, Multiscrape goes to work but totally fails because the information I’m after is not yet available.
So, the question is : can Multiscrape be told to WAIT for the full page to be shown, by monitoring the availability of some selector or other token ? Even a simple wait-time parameter would help, because the total scraping speed is of no importance to me (one scrape per day is all I need).

**Comment by danieldotnl** [comment]
Multiscrape just requests that page that is given in the url. It might be that a browser will load all kind of additional data with javascript but Multiscrape doesn't do that. If you need that additional data, you need to figure out (in the developer tools) which requests contains it and provide that as an url in your configuration.
