### ISSUE TITLE
The "OPEN HACS REPOSITORY ON MY.." points to incorrect repository.

### ISSUE THREAD

**Issue by BoneheadFraggle** [danieldotnl/ha-multiscrape#363]
..it points to ha-measureit, not ha-multiscrape
(https://my.home-assistant.io/redirect/hacs_repository/?owner=danieldotnl&repository=ha-measureit&category=integration)

**Comment by danieldotnl** [comment]
Thank for reporting this. MeasureIt is another integration of mine, I copied it from there :)
Fixed it now!
