### ISSUE TITLE
Execute a real-time scrape when someone is looking at the data

### ISSUE THREAD

**Issue by wigster** [danieldotnl/ha-multiscrape#37]
**Is your feature request related to a problem? Please describe.**
I would like to see up-to-date data when I actively look at the dashboard containing the output of a multi scale sensor, but would like to have a long scraping interval if I don’t. 

**Describe the solution you'd like**
not sure this is at all possible, but maybe there is some API in HASS that tells you if someone is logged in and looking at the dashboard in the browser/app. During that time, the scraping interval could be shortened to some user-set alternative so that up-to-date data appear in the plots and entity cards. Otherwise the intervals could be increased to be rare. Currently I have a rotten compromise interval of 15 minutes which is neither up to date when something sudden that causes me to log in happens, and also too detailed for my purpose of historical record. 

**Describe alternatives you've considered**
Cannot think of any.

**Comment by danieldotnl** [comment]
I see your point but I'm afraid it's hard to implement. Are you aware of any other integrations that have implemented similar functionality?
What about a service that triggers a refresh? You could add a button to your lovelace UI that will trigger the service manually.

**Comment by wigster** [comment]
No unfortunately I’ve not seen anything like this.

 But, regarding forcing a refresh, is there some service call I can make to multiscrape to make it scrape right now irrespective of the interval. That would be good enough for me!

**Comment by danieldotnl** [comment]
It's not there yet but I'll add it when I have time. (or create a pull request)

**Comment by yo-less** [comment]
First of all thanks for your work, your extension is just what I was looking for when I started integrating external data sources, this allows for much more efficient and customized scraping compared to what is offered by the internal scraper.

Slightly related to the request made above, I'd love to be able to reinitiate scraping at a specific point of time (midnight) as I'm using your multiscraper to pull weather forecast data from an external site and it would be nice to have the forecast for today and tomorrow updated at midnight. Right now it takes some time to update as I don't scrape as often as I would have to if I was using the internal scraper, which is really nice network-traffic-wise, but which creates a mismatch between the days and the info that is displayed.

**Comment by danieldotnl** [comment]
Check out [release 5.1.0](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v5.1.0)!!

**Comment by wigster** [comment]
Looks Great. Will play around with it!

**Comment by wigster** [comment]
So I am just trying to set this up. What I seem to have got is one service called

multiscape.reload

and then a separate service for each of the pages I am scraping

multiscape.wu_dejvice

am I right to understand that the first service reload everything while the individual reload just that one page?

in any case, the documentation refers to a multiscape.trigger service which doesn’t seem to be there.

**Comment by danieldotnl** [comment]
You are right, I made a mistake with the banking of the service. I'll release a fix soon. 
Anyway, it's the 2nd service you are mentioning.

**Comment by danieldotnl** [comment]
Fixed in v5.1.1

**Comment by danieldotnl** [comment]
@yo-less Does the new service work for you? You should now be able to schedule a refresh at midnight through an automation!

**Comment by wigster** [comment]
Ok everything works. Thanks!

Does multiscape.reload just trigger every integration in sequence or does it do something else?

**Comment by danieldotnl** [comment]
It's not related to triggering an update. It completely reloads everything including the configuration. It is used when you choose Multiscrape under Configuration -> Server Controls -> YAML configuration reloading.

**Comment by yo-less** [comment]
@danieldotnl This is absolutely amazing, thanks man. I've been using it for two days to see if there are any issues, but it's working as intended. It's great that every multiscrape instance can be assigned a name so that it's really easy to understand which service to call. Running an automation at midnight now and it takes 2 seconds to update the weather info, so it's pretty neat and functional. Weird that something as useful as this wasn't included in the core files of Home Assistant, but I guess that's what custom integrations are for... Keep up the great work 👍
