### ISSUE TITLE
release 7.0.2 does not have updated manifest.json

### ISSUE THREAD

**Issue by johntdyer** [danieldotnl/ha-multiscrape#389]
Two issues:

1. First the issue template suggests attaching const.py if you dont know the version number, however the version number isnt in const.py its in manifest.json

2. The latest tagged release still has 7.0.0 as the version in the manifest file

Thanks

**Comment by danieldotnl** [comment]
Thanks, I updated the issue template.
I forget to update the version in the manifest all the time, for me the github release is leading.
I guess I should look for something that updates the manifest automatically but it's not high on my prio list..
