### ISSUE TITLE
Feature Request: Option to preserve whitespace

### ISSUE THREAD

**Issue by Elderflowa** [danieldotnl/ha-multiscrape#409]
I will be honest here that i am a noob when it comes to the methods used in webscraping. 
Right now i have an issue where i am trying to scrape a YAML code snippet to preview in my HA, from an external Snippet Manager.

When it comes to indentation or whitespace however it keeps none and i would like to keep it so i can copy and paste from this attribute.

**Comment by danieldotnl** [comment]
Not fully clear to me. Is your question about yaml formatting or about an issue with scraping? If you need support, please post your questions on the community forum.

**Comment by Elderflowa** [comment]
When i am scraping i want to keep the formatting of new lines. My current output is one large text instead of the different paragraphs

**Comment by danieldotnl** [comment]
Maybe you should have a look at the release notes of [v7.2.0](https://github.com/danieldotnl/ha-multiscrape/releases/tag/v7.2.0). The only markup that can be scraped is html.
