### ISSUE TITLE
Error while setting up multiscrape platform for sensor.

### ISSUE THREAD

**Issue by J1A-T13N** [danieldotnl/ha-multiscrape#57]
## Version of the custom_component
pre-v5.5.0

## Configuration
Not yet

## Home Assistant Version
version | core-2021.9.2
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.8.5
os_name | Linux
os_version | 5.4.0-1028-raspi
arch | aarch64
timezone | Asia/Taipei

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

## Debug log

```text

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/multiscrape/sensor.py", line 42, in async_setup_platform
    if scraper.data is None:
UnboundLocalError: local variable 'scraper' referenced before assignment

```

**Comment by danieldotnl** [comment]
This is indeed a bug but I have only seen it occurring when the scraping url was not accessible when HA was starting up.

**Comment by J1A-T13N** [comment]
I fixed, Sorry is my fault, I don't follower your example configuration, 
I using your example configuration now it work for me.

thx you :')
