### ISSUE TITLE
Unable to get value

### ISSUE THREAD

**Issue by farberm** [danieldotnl/ha-multiscrape#75]
I installed the latest version via HACS. I log into Amerigas at the url given below and input my username and pw. On the next page that loads that returns is the Estimatedtank percentage. I used the Chrome, inspect, copy selector to get the select code below. I just want that value that is located in "Estimatedtank" in gallons. Not sure what I am doing wrong but I get an unknown. Error says the following...

Logger: custom_components.multiscrape.sensor
Source: custom_components/multiscrape/sensor.py:139
Integration: Multiscrape scraping component (documentation, issues)
First occurred: 10:20:05 PM (1 occurrences)
Last logged: 10:20:05 PM

Sensor Tankpercentage was unable to extract data from HTML

Here is my configuration code...

multiscrape:
  - resource: https://www.myamerigas.com/Login/Login?BrandId=002
    scan_interval: 3600
    headers:
        User-Agent: Mozilla/5.0
    form_submit:
      submit_once: True
      select: "form-control-valid"
      input:
        email: myloginemail
        password: mypassword
    sensor:
        - select: "#layoutDiv > main > div.container.pl-0.pr-0.pl-xl-3.pr-xl-3.pl-lg-3.pr-lg-3.pl-md-3.pr-md-3.pl-sm-0.pr-sm-0 > div:nth-child(2) > div.col-12.col-xl-6.col-lg-6.col-md-12.col-sm-12.pl-0.pr-0.pr-xl-3.pr-lg-3.pr-md-0.pr-sm-0 > div.col-12.bg-white.tankanddeliveries-padding.top-margin > div:nth-child(3) > div.col-12.col-xl-4.col-lg-4.col-md-12.col-sm-12.p-0.mt-3.EstimatedTankDiv > div > div.col-12.p-0.lblvalue-Estimatedtank"
          name: Tankpercentage

Thanks in advance

**Comment by farberm** [comment]
This is the CSS selector value from Safari...

  <div class="col-12 p-0 row mx-0">
                                    <div class="col-12 col-xl-4 col-lg-4 col-md-12 col-sm-12 p-0 mt-3 EstimatedTankDiv">
                                        <div class="col-12 col-xl-11 col-lg-11 col-md-12 col-sm-12 text-center quicklinks-height">
                                            <div class="col-12 p-0 lblvalue-Estimatedtank">
                                                61%

The error I am getting is the following still..
Error while setting up multiscrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/multiscrape/sensor.py", line 56, in async_setup_platform
    sensor_selector = Selector(hass, conf)
  File "/config/custom_components/multiscrape/selector.py", line 31, in __init__
    raise ValueError(
ValueError: Selector error: either select, select_list or a value template should be provided.

**Comment by danieldotnl** [comment]
If you don't manage to scrape the value you are looking for, please use the home assistant forum. I cannot give everyone personal assistance and please don't create github issues unless you are sure there is a bug.
Check the [wiki](https://github.com/danieldotnl/ha-multiscrape/wiki) for a scraping guide and other details on the functionality of this component.
